mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from stocks import views

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('stocks/', include('stocks.urls')),
    path('', views.aboutPage, name='Welcome')  
]

stocks/urls.py
from django.urls import path
from . import views

app_name = 'stocks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:stock_id>/', views.detail, name='detail'),
]

stocks/models.py
from django.db import models
import yfinance as yf 

class stock_data(models.Model):  
  stock_name = models.CharField(max_length=30)
  ticker = models.CharField(max_length=4)
  
  def __str__(self):
    return self.stock_name
  
  def stock_info(self):
    ticker = self.ticker
    return yf.Ticker(ticker)

  def stock_volume(self):
    week_history = self.stock_info().history(period='1wk')
    closest_volume = week_history['Volume'][4]   
    return closest_volume

  def getTicker(self):
    return self.ticker

stocks/forms.py
from django import forms
from stocks.models import stock_data

stocks/views.py
from django.shortcuts import render
from django.views import generic
from django.http import JsonResponse
from .models import stock_data
from stocks.GN import newsList
import math
import pandas as pd

class IndexView(generic.ListView):
  template_name = 'stocks/index.html'
  context_object_name = 'latest_ticker_list'

  def get_queryset(self):
    return stock_data.objects.all()
  
def aboutPage(request):
  return render(request, 'stocks/about.html')

def detail(request, stock_id):
    stock_ticker = stock_data.objects.get(pk=stock_id).getTicker()
    stock_history = stock_data.objects.get(pk=stock_id).stock_info().history(period='max',interval='1d')  # Creates and gets the history for a yfinance object
    df = pd.DataFrame(stock_history['Close'].items())
    df1 = df.dropna().set_index(1) # Uses a pandas dataframe in order to avoid nan values
    stock_information = df1.itertuples()  # Stores that formatted data in a single variable / map 
    title = stock_data.objects.get(pk=stock_id).ticker
    todayDate = df1.iloc[-1][0]
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':  # checks if AJAX request, .is_ajax() deprecated
        news = request.POST.get('dateOfClick')  # Gets the post data from the AJAX function in detail.html
        newsListings = newsList(news, news, stock_ticker)
        return JsonResponse({'newsList': newsListings}, status=200)
    return render(request, 'stocks/detail.html',
                  {'stock_information': stock_information, 'title': title, 'currentDate': todayDate})

stocks/templates/stocks/about.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Tech stock Timeline</title>

<style>

body {background-color: #2460A7FF}
h1   {color: blue;}
p    {color: red;}

</style>

</head>

<body>
	<div id="title" style="color: #FFFFFF; text-align:center; font-size: 60px"> Tech Stock Timeline
  
  <table>
    <ul class = "main_menu">
    <li><a href = "stocks/" style="font-size: 30px;"> See Current List of Stocks</a></li>
    <li><a href = "stocks/new" style="font-size: 30px;"> Add a new Stock</a></li>
    </ul>
  </table>
 
  </div>
</body>
{% load static %}
<link rel="stylesheet" href={% static "stocks/about.css" %}>

</html>

stocks/templates/stocks/detail.html
<html>
<head>
    {% load static %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static 'stocks/jquery-3.5.1.js' %}"></script>
    <script type="text/javascript">
        {% block javascript %}
            $(document).ready(function () {
                const csrf = $("input[name='csrfmiddlewaretoken']").val();
               
                function MMDDYYYY(date) {
                    return ((date.getMonth() > 8) ? (date.getMonth() + 1) : ('0' + (date.getMonth() + 1))) + '/' + ((date.getDate() > 9) ? date.getDate() : ('0' + date.getDate())) + '/' + date.getFullYear()
                } // function allows date objects to be converted to a format google news can handle

                let storedData = [MMDDYYYY(new Date('{{ currentDate | safe }}'))];
                console.log(storedData);

                google.charts.load('current', {'packages': ['corechart']});
                google.charts.setOnLoadCallback(drawChart);

                function drawChart() {
                    var data = new google.visualization.DataTable();
                    data.addColumn('date', 'TimeStamp');
                    data.addColumn('number', 'Value');
                    {% for price, date in stock_information %}
                        data.addRow([new Date('{{ date|safe }}'), {{ price|safe }}]);
                    {% endfor %}

                    var options = {
                        title: '{{ title }} stock over time',
                        hAxis: {title: 'Year', titleTextStyle: {color: '#333'}},
                        vAxis: {minValue: 0}
                    };

                    function postData(event) { // Users ajax to get the data and add it to the unordered list for the news for the date
                        console.log("postData function is running"); // check when function is being called
                        $.ajax({
                            url: '',
                            type: 'POST',
                            data: {
                                dateOfClick: MMDDYYYY(storedData[0]),
                                csrfmiddlewaretoken: csrf
                            },
                            success: function (response) {
                                if (response.newsList[0] !== '' && response.newsList[0] !== undefined && response.newsList[0] !== null){
                                    $("#news").append('<li>' + response.newsList[0] + '</li>')
                                }
                                if (response.newsList[0] === undefined){
                                    $("#news").append('<li> No news from this date! </li>')
                                }
                            }
                        })

                    }

                    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));

                    function selectHandler() { // Gets the selected date from the graph of the stock
                        var selectedItem = chart.getSelection()[0];
                        if (selectedItem) {
                            var value = data.getValue(selectedItem.row, 0);
                            storedData[0] = value;
                            postData();
                        }
                    }

                    google.visualization.events.addListener(chart, 'select', selectHandler)
                    chart.draw(data, options);
                }
            })
            </script>
        {% endblock %}
</head>
<div>
    <div id="chart_div" style="width: 50%; height: 500px;"></div>
    <div id="content" style='width: 50%;'></div>
</div>
<body>
{% csrf_token %}

<ul id='news'>
</ul>
</body>
</html>

stocks/templates/stocks/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stocks/indexstyle.css' %}">
<script src = "{% static 'stocks/sidebar.js'%}" type="text/javascript"></script>
<body>
    <div class="sidebar" id="mySidebar">
      <button class="closing button" onclick="bar_close()" style="width:100%; background-color:#263938; color:#fdeed2">Close &times;</button>
      <ul><a href="about/" class="button">About</a></ul>
      <ul><a href="/" class="button">Home</a></ul>
      <ul><a href="#" class="button">Link 3</a></ul>
    </div>
    <div id = "main">
      <div class="teal">
      <button id="openNav" class="buttontealxlarge" onclick="bar_open()" style="width:50px; height:50px;">&#9776;</button>
      <div class="container">
    </div>
    <div class = "content">
      <h4><font size = '+10'>Technology Companies' Stock Data</font></h4>
      {% if latest_ticker_list %}
        <ul>
        {% for ticker in latest_ticker_list %}
            <li><a href="{% url 'stocks:detail' ticker.id %}">{{ ticker.stock_name }}</a>
                Current volume: {{ ticker.stock_volume }}</li>
            {%endfor%}
            </ul>
        {% else %}
            <p> No stocks are available. </p>
        {% endif %}
    </div>
  </div>
</body>